- name: Deploy Flask app with Docker
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Clone GitHub repository
      git:
        repo: https://github.com/lucaslimafernandes/Flask_DA.git
        dest: "{{ playbook_dir }}/Flask_DA"
        accept_hostkey: yes
        force: yes

    - name: Build Docker image
      command: docker build -t flask-app ./Flask_DA

    - name: Run Docker container
      docker_container:
        name: flask-app-container
        image: flask-app
        ports:
          - "5099:5099"
        state: started
