- name: Deploy Flask app with Docker
  hosts: oracle
  remote_user: ansible
  become: true

  tasks:
    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true
      register: docker_check

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_check.rc != 0

    - name: Add ansible user to the docker group
      user:
        name: ansible
        groups: docker
        append: yes
      when: docker_check.rc == 0

    - name: Clone GitHub repository
      git:
        repo: https://github.com/lucaslimafernandes/Flask_DA.git
        dest: /home/ansible/Flask_DA
        accept_hostkey: yes
        force: yes

    - name: Build Docker image
      command: docker build -t flask-app .

    - name: Run Docker container
      docker_container:
        name: flask-app-container
        image: flask-app
        ports:
          - "5099:5099"
        state: started
